### ISSUE TITLE
Layout, Section & Styling

### ISSUE THREAD

**Issue by hanacaraka** [mesfint/portfolio#4]
1. Font size is too small to read using mobilephone. It is better to make the font size bigger.
2. The "Projects" section should replace the "Skills" section.
3. Based on Joshua Fluke's recommendation about portfolio in his YouTube video: "Skills" section with its indicator skill level should be omitted in portfolio and resume/CV. He further explains that it is better the recruiter/hiring manager knows your skill only after you take their coding/programming test.
4. The first line or title in each project's display for Product Landing Page and Survey Form need to adjust into center alignment.
5. The rectangles inside the Hot and Cold project display need to adjust into center alignment.
6. The contact info on portfolio's owner should be under the name of portfolio's owner, make it easy for people to see the contact info in case they want to reach out. The contact info that is essential: email address, LinkedIn, GitHub, blog (Medium/Dev.to/personal blog that is self-hosted). As for Twitter and other social media are optional.

**Comment by mesfint** [comment]
Wow...I really appreciate for taking your time and give me such detailed feedback, I will address all these issues. BW, I am working hard to improve the portfolio at the moment and trying to implement Sass( a little bit advanced CSS) for the overall consistency and appealing features...I will send you the link as I finish the changes. Cheers
